/**
 * Code generation — produces TypeScript type definitions from JSON Schema
 * files discovered via the entity folder convention.
 *
 * Uses `json-schema-to-typescript` to compile each entity's `schema.json`
 * into a TypeScript interface.
 *
 * Naming convention:
 * - Nodes:  `{PascalName}Data`       (e.g. `TaskData`)
 * - Edges:  `{PascalName}EdgeData`   (e.g. `HasStepEdgeData`)
 */

import type { DiscoveryResult } from '../types.js';

function pascalCase(s: string): string {
  return s.replace(/(^|[^a-zA-Z0-9])([a-zA-Z])/g, (_, _sep, ch) =>
    ch.toUpperCase(),
  );
}

export interface CodegenOptions {
  /** Add banner comment at top of output. Defaults to true. */
  banner?: boolean;
}

/**
 * Generate TypeScript type definitions from a DiscoveryResult.
 * Returns the full file content as a string.
 */
export async function generateTypes(
  discovery: DiscoveryResult,
  options: CodegenOptions = {},
): Promise<string> {
  // Lazy-load to avoid requiring this dep at runtime for non-codegen usage
  const { compile } = await import('json-schema-to-typescript');

  const { banner = true } = options;
  const chunks: string[] = [];

  if (banner) {
    chunks.push(
      '// Auto-generated by firegraph codegen — do not edit manually\n',
    );
  }

  // Sort for deterministic output
  const sortedNodes = [...discovery.nodes.entries()].sort(([a], [b]) =>
    a.localeCompare(b),
  );
  const sortedEdges = [...discovery.edges.entries()].sort(([a], [b]) =>
    a.localeCompare(b),
  );

  for (const [name, entity] of sortedNodes) {
    const typeName = `${pascalCase(name)}Data`;
    const ts = await compile(entity.schema as any, typeName, {
      bannerComment: '',
      additionalProperties: false,
    });
    chunks.push(ts.trim());
    chunks.push('');
  }

  for (const [name, entity] of sortedEdges) {
    const typeName = `${pascalCase(name)}EdgeData`;
    const ts = await compile(entity.schema as any, typeName, {
      bannerComment: '',
      additionalProperties: false,
    });
    chunks.push(ts.trim());
    chunks.push('');
  }

  return chunks.join('\n').trimEnd() + '\n';
}
